name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-build:
    runs-on: arc-runner-set
    container: golang
    steps:
    - uses: actions/checkout@v4
    - name: ls
      run: ls -la
