name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-build:
    runs-on: arc-runner-set
    container: golang
    steps:
    - run: git clone https://github.com/richardpct/go-hostname
