name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-job-01:
#    runs-on: arc-runner-set
    runs-on: self-hosted
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      - run: mkdir /toto
      - run: whoami
