name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: rpct-test
    steps:
    - name: hello
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        curl https://www.google.fr

#  container-build:
#    runs-on: rpct-test
#    container: golang
#    steps:
#    - uses: actions/checkout@v4
#    - name: build
#      run: |
#        go mod init example/hello
#        go mod tidy
#        go build -buildvcs=false -o hello .
#        ls -la
#    - name: upload binary
#      uses: actions/upload-artifact@v4
#      with:
#        name: hello
#        path: |
#          hello

#  container-exec:
#    needs: container-build
#    runs-on: rpct-test
#    container: nginx
#    steps:
#    - name: test
#      run: |
#        apt-get update
#        apt-get upgrade -y
#        apt-get install -y vim
#    - name: Download
#      uses: actions/download-artifact@v5
#      with:
#        name: hello
#    - name: exec
#      run: |
#        ls -la
#        chmod 755 hello
#        ls -la
#        ./hello

  buildah-build:
    runs-on: rpct-test
    container:
      image: quay.io/buildah/stable:latest
      # Important in ARC: match the workspace owner or ensure fsGroup in RRS
      options: --user 1001:1001
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildah (no mounts)
        env:
          XDG_RUNTIME_DIR: ${{ github.workspace }}/.xdg
        run: |
          # Prepare writable dirs under the workspace
          ROOT="$GITHUB_WORKSPACE/.containers/storage"
          RUNROOT="$GITHUB_WORKSPACE/.containers/runroot"
          mkdir -p "$ROOT" "$RUNROOT" "$XDG_RUNTIME_DIR"

          # Sanity: show who we are and what driver Buildah will use
          id
          buildah --version

          buildah --storage-driver vfs --root "$ROOT" --runroot "$RUNROOT" \
            bud -t registry.example.com/app:0.1 .
