name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-job-01:
    runs-on: arc-runner-set
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      - run: mkdir /toto
      - run: whoami
  container-job-02:
    runs-on: arc-runner-set
    container: node
    steps:
      - run: node --version
      - run: npm --version
      - run: mkdir /titi
      - run: whoami
