name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-build:
    runs-on: arc-runner-set
    container: golang
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        go mod init
        go build -o go-hostname
