name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: arc-runner-set
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
