name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  container-job-01:
    runs-on: runner-test-04
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      - run: sleep 120
  container-job-02:
    runs-on: runner-test-04
    container: node
    steps:
      - run: node --version
      - run: npm --version
      - run: sleep 120
